# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tomas/src/dab/hdl/projects/fmcomms2/zed/fmcomms2_zed.srcs/sources_1/bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0.xci
# IP: The module: 'system_axi_ad9361_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tomas/src/dab/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0_pps_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9361_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tomas/src/dab/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_ad9361_0/bef3/up_xfer_cntrl_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9361_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tomas/src/dab/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_ad9361_0/bef3/ad_rst_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9361_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tomas/src/dab/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_ad9361_0/bef3/up_xfer_status_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9361_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tomas/src/dab/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_ad9361_0/bef3/up_clock_mon_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9361_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tomas/src/dab/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_ad9361_0/axi_ad9361_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9361_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/tomas/src/dab/hdl/projects/fmcomms2/zed/fmcomms2_zed.srcs/sources_1/bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0.xci
# IP: The module: 'system_axi_ad9361_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tomas/src/dab/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0_pps_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9361_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tomas/src/dab/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_ad9361_0/bef3/up_xfer_cntrl_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9361_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tomas/src/dab/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_ad9361_0/bef3/ad_rst_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9361_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tomas/src/dab/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_ad9361_0/bef3/up_xfer_status_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9361_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tomas/src/dab/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_ad9361_0/bef3/up_clock_mon_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9361_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tomas/src/dab/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_ad9361_0/axi_ad9361_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ad9361_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
